nome = input('Digite seu nome completo: ')
print("="*5, nome.upper(), '='*5)
print('='*5, nome.lower(), '='*5)
espaços = nome.split()
letras = ''.join(espaços)
print('Seu nome completo tem', len(letras), 'letras')
print('Seu primeiro nome tem', len(espaços[0]), 'letras')