times = ('ASA', 'Lagarto', 'Jacuipense', 'Juazeirense', 'Santa Cruz', 'CSE', 'Atlético - BA', 'Sergipe')
print('=-' * 30)
print('{: ^60}'.format(' GRUPO D 20/06/2022 '))
print('=-' * 30)
print(f'Colocação na tabela: {times}')
print('- - ' * 30)
print(f'Os 4 primeiros colocados: {times[0:4]}')
print('- - ' * 30)
print(f'Os 2 na zona do rebaixamento: {times[6:]}')
print('- - ' * 30)
print(f'O infeliz do Santa Cruz estar na {times.index("Santa Cruz") + 1}° posição')
print('- - ' * 30)
print(f'O grupo em ordem alfabética fica: {sorted(times)}')
print('- - ' * 30)
